### PR TITLE
Issue #20, fix firefox's back button

### PR DESCRIPTION
**Pull request by buksy90**
Proposed fix for Firefox's issue https://github.com/officert/vue-friendly-iframe/issues/20

### CODE REVIEW

**Comment by buksy90** [comment]
Hello @officert & @shaneparsons, any chance you could merge this PR and release a new version?

**Comment by shaneparsons** [comment]
@buksy90 I don’t have any kind of authority in this repo.

**Comment by buksy90** [comment]
Hey @officert, any update on this PR ?

**Comment by officert** [comment]
Sorry for the delay, thanks @buksy90 !

**Comment by officert** [comment]
Published in v0.18.0

**Pull request merged**
